### ISSUE TITLE
issue with defining HmacSHA256

### ISSUE THREAD

**Issue by namoopsoo** [danieljoos/aws-sign-web#3]
* Hello there. I'm trying out your library and I ran into this error on the console, 

![image](https://cloud.githubusercontent.com/assets/2048242/24074998/bef15b98-0be9-11e7-8f9e-c0e954191b93.png)

* The context appears to be ...
```javascript
// excerpt from aws-sign-web.js
            hmac: function (key, input, options) {
                options = extend({hexOutput: true, textInput: true}, options);
                var hmac = CryptoJS.HmacSHA256(input, key, {asBytes: true});    // Line 286
                if (options.hexOutput) {
                    return hmac.toString(CryptoJS.enc.Hex);
                }
                return hmac;
            }
```
* **Potential culprit**: I am leaving out the `sessionToken`. I am not sure if you require that? I have used _Signature Version 4_ with a _Python_ implementation which did not require this.
* Also, I forgot to mention, I changed my `vanilla.html` setup to also include `core.js`, because errors were complaining about `CryptoJS` undefined in `sha256.js`
```
	<script src="js/core.js"></script>
	<script src="js/sha256.js"></script>
	<script src="js/hmac-sha256.js"></script>
	<script src="js/aws-sign-web.js"></script>
```

Please let me know if I can provide more details.

**Comment by namoopsoo** [comment]
I am realizing that this is some fundamental problem with how `CryptoJS.HmacSHA256` is called, because I'm seeing the same error in isolation, 
```javascript
CryptoJS.HmacSHA256("Message", "Key")
core.js:726 Uncaught TypeError: Cannot read property 'init' of undefined
    at Object.HmacSHA256 (core.js:726)
    at <anonymous>:1:10
```

**Comment by namoopsoo** [comment]
Ok instead of including one crypto-js `.js` file at a time until it worked, I just put everything up there and now the sample code throws no errors. So I guess I am good for now. 

One thing I did need is to add `"jshint": "^2.9.4",` to the `package.json`, or else I was getting one of these warnings during `npm install`...
```
└── UNMET PEER DEPENDENCY jshint@2.x

npm WARN gulp-jshint@2.0.4 requires a peer of jshint@2.x but none was installed.
```

**Comment by danieljoos** [comment]
Hi there,

Thanks for sharing this issue. There is a version of the CryptoJS library (https://github.com/sytelus/CryptoJS) that provides "rollup" files that include the "core" plus a certain sublibrary (e.g. SHA256). When you include those "rollup" files instead of the normal CryptoJS files, the problems with initialization should be gone. You can also include CryptoJS completely, but it is quite big and only the SHA256 and HMAC-SHA256 are required for `aws-sign-web`.

`jshint` is required by `gulp-jshint` as peer-dependency. You can install any jshint 2. Anyway, those `gulp-*` packages are only used to minify the the script. If you only like to use `aws-sign-web` then install the package with `npm install --only=production`.

Cheers,
Daniel

**Comment by weiliang903** [comment]
"crypto-js": {
      "main": [
        "core.js",
        "crypto-js.js",
        "md5.js",
        "sha1.js",
        "enc-base64.js",
        "sha256.js",
        "hmac-sha256.js"
      ]
I've had the same problem.
